// <auto-generated />
using CFS_1507.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CFS_1507.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250715050748_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CFS_1507.Domain.Entities.LanguageEntity", b =>
                {
                    b.Property<string>("language_id")
                        .HasColumnType("text");

                    b.Property<string>("language_code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("language_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("language_id");

                    b.ToTable("LanguageEntities");

                    b.HasData(
                        new
                        {
                            language_id = "0196cce9-cadf-704d-bdcf-9edec1fc115d",
                            language_code = "vi-VN",
                            language_name = "Tiếng Việt"
                        },
                        new
                        {
                            language_id = "0196cce9-cadf-7881-894d-b4a5ac0889ff",
                            language_code = "en-US",
                            language_name = "English"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
