// <auto-generated />
using System;
using CFS_1507.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CFS_1507.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250717083445_InitDB07")]
    partial class InitDB07
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CFS_1507.Domain.Entities.AttachToEntity", b =>
                {
                    b.Property<string>("attach_to_id")
                        .HasColumnType("text");

                    b.Property<string>("role_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("attach_to_id");

                    b.HasIndex("role_id");

                    b.HasIndex("user_id");

                    b.ToTable("AttachToEntities");
                });

            modelBuilder.Entity("CFS_1507.Domain.Entities.BlackListEntity", b =>
                {
                    b.Property<string>("blacklist_id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("create_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("token_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("blacklist_id");

                    b.HasIndex("user_id");

                    b.ToTable("BlackListEntities");
                });

            modelBuilder.Entity("CFS_1507.Domain.Entities.LanguageEntity", b =>
                {
                    b.Property<string>("language_id")
                        .HasColumnType("text");

                    b.Property<string>("language_code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("language_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("language_id");

                    b.ToTable("LanguageEntities");

                    b.HasData(
                        new
                        {
                            language_id = "0196cce9-cadf-704d-bdcf-9edec1fc115d",
                            language_code = "vi-VN",
                            language_name = "Tiếng Việt"
                        },
                        new
                        {
                            language_id = "0196cce9-cadf-7881-894d-b4a5ac0889ff",
                            language_code = "en-US",
                            language_name = "English"
                        });
                });

            modelBuilder.Entity("CFS_1507.Domain.Entities.ProductEntity", b =>
                {
                    b.Property<string>("product_id")
                        .HasColumnType("text");

                    b.Property<string>("product_image")
                        .HasColumnType("text");

                    b.Property<string>("product_name")
                        .HasColumnType("text");

                    b.Property<double?>("product_price")
                        .HasColumnType("double precision");

                    b.HasKey("product_id");

                    b.ToTable("ProductEntities");
                });

            modelBuilder.Entity("CFS_1507.Domain.Entities.RoleEntity", b =>
                {
                    b.Property<string>("role_id")
                        .HasColumnType("text");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("role_id");

                    b.ToTable("RoleEntities");
                });

            modelBuilder.Entity("CFS_1507.Domain.Entities.UserEntity", b =>
                {
                    b.Property<string>("user_id")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("hashPassWord")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("user_id");

                    b.ToTable("UserEntities");
                });

            modelBuilder.Entity("CFS_1507.Domain.Entities.AttachToEntity", b =>
                {
                    b.HasOne("CFS_1507.Domain.Entities.RoleEntity", "Role")
                        .WithMany("AttachTos")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CFS_1507.Domain.Entities.UserEntity", "User")
                        .WithMany("AttachToEntities")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CFS_1507.Domain.Entities.BlackListEntity", b =>
                {
                    b.HasOne("CFS_1507.Domain.Entities.UserEntity", "User")
                        .WithMany("BlackListEntities")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CFS_1507.Domain.Entities.RoleEntity", b =>
                {
                    b.Navigation("AttachTos");
                });

            modelBuilder.Entity("CFS_1507.Domain.Entities.UserEntity", b =>
                {
                    b.Navigation("AttachToEntities");

                    b.Navigation("BlackListEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
